Portfolio page
wale-prog/My-porfolio pull request #2
Opened 2022-03-22 12:17 UTC by wale-prog

A portfolio and About me pages have been added to be merged with the introduction page earlier added to the main branch.

2022-03-22 17:33 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @wale-prog,

Good job so far!
✔️ Good documentation
✔️ Nice design
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 17:33 UTC, TedLivist commented on index.html
> +            <p class="portfolio-heading">My Recent Work</p>
- [ ] In keeping with semantic principles, this header should be appropriately wrapped using the **`hx`** tag, not **`p`** tag. Kindly refactor.

2022-03-22 17:33 UTC, TedLivist commented on index.html
> +        <img src="images/Group.png" alt="">
- [ ] Decorations should be background-images (in CSS), not `img` tags. Kindly remove this image here and implement the decoration using CSS.

2022-03-22 17:33 UTC, TedLivist commented on style.css
> +}
- [ ] Kindly ensure that your button color effects for hover, active (pressed) and disabled are all implemented as we have in the Figma design

  ![buttons-color](https://user-images.githubusercontent.com/36542986/159539913-8d731507-699b-4238-b619-d36566162328.jpg)

2022-03-22 17:33 UTC, TedLivist commented on index.html
> +        <a href="#" class="btn skill-list-btn container">Get My Resume</a>
- [ ] Kindly ensure that the button effects highlighted in the design are implemented.

  ![buttons-color](https://user-images.githubusercontent.com/36542986/159540902-6d65b5ad-328f-49a3-b6cb-593bc3705b75.jpg)

2022-03-23 03:26 UTC, mateo951 approved these changes
### Hi @wale-prog,

Nice job making all the necessary changes requested by the previous reviewer 🔥
Your project is complete!  There is nothing else to say other than... it's time to merge it ✔ 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 03:26 UTC, mateo951 commented on index.html
> +            <h1 class="portfolio-heading">My Recent Work</h1>
Addressed ✔

2022-03-23 03:26 UTC, mateo951 commented on style.css
> +}
Addressed 🚀

2022-03-23 08:11 UTC, merged